/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author antergos
 */
public class Pruebas extends javax.swing.JFrame {

    /**
     * Creates new form Pruebas
     */
    public Pruebas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSuperior = new javax.swing.JPanel();
        pnlFondo = new javax.swing.JPanel();
        pnlCuadro = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        ckbRemember = new javax.swing.JCheckBox();
        btnSesion = new javax.swing.JButton();
        btnForgot = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        lblPass = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        pnlSuperior.setBackground(new java.awt.Color(182, 182, 182));
        pnlSuperior.setLayout(null);
        getContentPane().add(pnlSuperior);
        pnlSuperior.setBounds(0, 0, 910, 50);

        pnlFondo.setBackground(new java.awt.Color(254, 254, 254));
        pnlFondo.setMinimumSize(new java.awt.Dimension(1092, 648));
        pnlFondo.setPreferredSize(new java.awt.Dimension(1092, 658));
        pnlFondo.setLayout(null);

        pnlCuadro.setBackground(new java.awt.Color(183, 183, 183));
        pnlCuadro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlCuadro.setLayout(null);

        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlCuadro.add(txtUser);
        txtUser.setBounds(200, 30, 220, 40);

        ckbRemember.setText("Recordar nombre de usuario");
        pnlCuadro.add(ckbRemember);
        ckbRemember.setBounds(120, 120, 240, 23);

        btnSesion.setText("Iniciar sesión");
        pnlCuadro.add(btnSesion);
        btnSesion.setBounds(320, 178, 140, 30);

        btnForgot.setText("Recuperar contraseña");
        btnForgot.setBorderPainted(false);
        pnlCuadro.add(btnForgot);
        btnForgot.setBounds(10, 180, 190, 31);
        pnlCuadro.add(txtPass);
        txtPass.setBounds(200, 70, 220, 40);

        lblPass.setText("Contraseña");
        pnlCuadro.add(lblPass);
        lblPass.setBounds(90, 70, 90, 40);

        lblUser.setText("Nombre de usuario");
        pnlCuadro.add(lblUser);
        lblUser.setBounds(39, 30, 160, 40);

        pnlFondo.add(pnlCuadro);
        pnlCuadro.setBounds(70, 230, 470, 220);

        getContentPane().add(pnlFondo);
        pnlFondo.setBounds(0, 0, 910, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pruebas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForgot;
    private javax.swing.JButton btnSesion;
    private javax.swing.JCheckBox ckbRemember;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlCuadro;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlSuperior;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
