/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.proyectorat.view;
import com.proyectorat.manager.Preferences;
import com.proyectorat.manager.Temporal;
import com.proyectorat.manager.EmpresaManagerImpl;
import com.proyectorat.manager.MD5;
import com.proyectorat.manager.UsuarioManagerImpl;
import com.proyectorat.model.Empresa;
import com.proyectorat.model.Usuario;
import java.awt.HeadlessException;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author mateo
 */
public class JIFLoginUsuario extends javax.swing.JInternalFrame {

    UsuarioManagerImpl nu = new UsuarioManagerImpl();
    static EmpresaManagerImpl ne = new EmpresaManagerImpl();
    Usuario usuarioVO = new Usuario();
    static Empresa empresaVO = new Empresa();
    Preferences pref = new Preferences();
    Temporal tmp;
    
    public JIFLoginUsuario(Empresa empresaVO) {

        JIFLoginUsuario.empresaVO.setId_empresa(empresaVO.getId_empresa());
        JIFLoginUsuario.empresaVO.setNombre(empresaVO.getNombre());
        JIFLoginUsuario.empresaVO.setLogo(empresaVO.getLogo());
        JIFLoginUsuario.empresaVO.setEstado(empresaVO.getEstado());
        
        try {
            this.tmp = new Temporal();
        } catch (IOException ex) {
        }
        initComponents();
        if(empresaVO.getLogo()!=null) {
            lblLogo.setIcon(new ImageIcon(empresaVO.getLogo()));
        } else {
            lblLogo.setIcon(new ImageIcon(getClass().getResource("/com/resources/img/RAT.png")));
        }
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblChange = new javax.swing.JLabel();
        lblUsu = new javax.swing.JLabel();
        txtUsu = new javax.swing.JTextField();
        lblCon = new javax.swing.JLabel();
        txtCon = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl1.setBackground(new java.awt.Color(189, 195, 199));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(44, 62, 80));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Iniciar sesión");

        lblChange.setText("Cambiar de empresa");
        lblChange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChangeMouseClicked(evt);
            }
        });

        lblUsu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsu.setForeground(new java.awt.Color(44, 62, 80));
        lblUsu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsu.setText("Nombre de usuario");

        txtUsu.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblCon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCon.setForeground(new java.awt.Color(44, 62, 80));
        lblCon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCon.setText("Contraseña");

        txtCon.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnLogin.setText("Iniciar sesión");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblUsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblCon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblChange))
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(txtUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                        .addComponent(txtCon, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addGap(135, 135, 135))))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(lblChange)
                .addContainerGap())
        );

        getContentPane().add(pnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 370, 280));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 320));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/img/home.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1087, 643));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeMouseClicked
        pref.saveProp("Recordar empresa", "false");
        JIFLoginEmpresa loginEmpresa = new JIFLoginEmpresa();
        Main.jDesktopPane1.add(loginEmpresa);
        loginEmpresa.toFront();
        loginEmpresa.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblChangeMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        if("".equals(txtUsu.getText())){
            JOptionPane.showMessageDialog(null, "Ingrese el nombre de usuario", "Campo vacío", JOptionPane.WARNING_MESSAGE);
            return;
        } if ("".equals(txtCon.getText())) {
            JOptionPane.showMessageDialog(null, "Ingrese la contraseña", "Campo vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String usu = txtUsu.getText();
        String con = txtCon.getText();
        String conEncripted = MD5.encriptMD5(con);
        try {
            usuarioVO = nu.getUsuario(usu, Integer.parseInt(empresaVO.getId_empresa()));
            if(conEncripted.equals(usuarioVO.getClave())) {
                if (usuarioVO.getPerfil().equals("Administrador")) {
                    JIFInicioAdmin inicioAdmin = new JIFInicioAdmin(empresaVO, usuarioVO);
                    Main.jDesktopPane1.add(inicioAdmin);
                    inicioAdmin.toFront();
                    inicioAdmin.setVisible(true);
                    dispose();
                    System.out.println("Sesión de administrador iniciada");
                } else {
                    JIFInicio inicio = new JIFInicio(empresaVO, usuarioVO);
                    Main.jDesktopPane1.add(inicio);
                    inicio.toFront();
                    inicio.setVisible(true);
                    dispose();
                    System.out.println("Sesión estandar iniciada");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Nombre de usuario y/o contraseña incorrecta.", "Error de credenciales", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, ""+ e + "\n" + empresaVO.getId_empresa());
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblCon;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsu;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPasswordField txtCon;
    private javax.swing.JTextField txtUsu;
    // End of variables declaration//GEN-END:variables
}
